In [5]:
import numpy as np

np.random.rand(3, 4)

array([[0.87946721, 0.50493063, 0.13782347, 0.48840983],
       [0.50838055, 0.80761706, 0.02185112, 0.42864488],
       [0.72603624, 0.0607603 , 0.96241574, 0.71433899]])

In [6]:
import numpy as np

data = np.random.rand(3, 4) # 3x4 행렬에 난수 생성
print(data)

list = [3, 4.1, 5, 6.3, 7, 8.6] # 단일 리스트
arr = np.array(list)

print('평균', arr.mean())
print('합계', arr.sum())
print('최대값', arr.max())
print('최소값', arr.min())
print('분산', arr.var())
print('표준편차', arr.std())

[[0.10001438 0.40710934 0.30644926 0.91893113]
 [0.79923528 0.55344957 0.39429544 0.55206534]
 [0.32404808 0.55360258 0.43441295 0.37961915]]
평균 5.666666666666667
합계 34.0
최대값 8.6
최소값 3.0
분산 3.465555555555555
표준편차 1.8616002673924268
